server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false&characterEncoding=utf-8
    username: root
    password: 123456
    platform: mysql
    hikari:
      max-lifetime: 5000000
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      port: 35730