server:
  port: 7001

spring:
  application:
    name: eureka-server-7001
  devtools:
    livereload:
      port: 35732
eureka:
  instance:
    hostname: localhost
  client:
    # false不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，我的指责就是维护服务实例，并不需要检索服务
    fetch-registry: false
    service-url:
      #设置与eurkeka server交互的地址 查询和注册都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/