server:
  port: 7001

spring:
  application:
    name: eureka-server-7001
  devtools:
    livereload:
      port: 35732
eureka:
  instance:
    hostname: eureka7001.com
  client:
    # false不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，我的指责就是维护服务实例，并不需要检索服务
    fetch-registry: false
    service-url:
      # 设置与eureka server交互的地址 查询和注册都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/
  server:
    # 关闭eureka自我保护机制，立马将不可用服务剔除
    enable-self-preservation: false
    # 60秒剔除
    eviction-interval-timer-in-ms: 90000
